### ISSUE TITLE
Support for MALMEN

### ISSUE THREAD

**Issue by Yzk1114** [zjunlp/EasyEdit#116]
MALMEN: Massive Language Model Editing Network [https://arxiv.org/abs/2311.04661](url) is the newest SOTA on Meta Learning method. In their experiments, it has the excellent performance with massive editing even better than MEMIT in certain aspects. I think it is a combination of MEND and MEMIT. May you add support for this method? Thank you! [https://github.com/ChenmienTan/malmen](url)

**Comment by zxlzr** [comment]
We will support MALMEN soon, thank you for your suggestions.

**Comment by zxlzr** [comment]
Hi, the support for MALMEN is performing internal testing of the code and aiming for release within a month.

**Comment by xzwyyd** [comment]
I apologize for the delay. Currently, `Easyedit` has implemented partial support for the `Malmen` method, but due to framework compatibility issues, there are some performance compromises in certain functions. We will continue to improve support in the first half of the year. Thank you for your patience.

**Comment by xzwyyd** [comment]
We sincerely apologize for the inconvenience. Due to certain compatibility issues between our framework and the original MALMEN code, we can only provide partial support at this time. We’ve found that performance is relatively stable when the batch size is set to 1, but when the batch size is greater than 1, there is a noticeable performance drop. Despite multiple attempts, we believe the issue may be related to our data loading process. However, given the complexity of modifying the framework and our resource limitations, we’ve decided not to pursue further optimization in this area for the time being.
We greatly appreciate your attention to this issue and your valuable feedback. If you have any better solutions or ideas, we warmly welcome you to submit a PR to our GitHub repository. We would be delighted to see contributions from the community to help improve the quality of the project.
