### ISSUE TITLE
support KE model for llama-7B

### ISSUE THREAD

**Issue by quqxui** [zjunlp/EasyEdit#122]
Hi, Do you plan to support KE model editing with llama as the Backbone?  I only found hparams of T5 and GPT-J.

**Comment by zxlzr** [comment]
Hi, we found supporting  KE for llama-7B is quite difficult, but we will try it later. 

Happy new year.

**Comment by whitepapercg** [comment]
> Hi, we found supporting KE for llama-7B is quite difficult, but we will try it later.
> 
> Happy new year.

Hi and Merry Christmas! Apparently you have started to introduce llama support, is there any chance we will see an implementation for consumer PCs (12/24gb VRAM req)?

**Comment by tbozhong** [comment]
According to the paper's findings, it can be observed that the performance of KE in editing on llama-based MLLM (e.g. MiniGPT-4) is also unsatisfactory.

**Comment by zxlzr** [comment]
Hi, we would like to close this issue since we found supporting KE in EasyEdit is a bit complicated now. You can run KE with the code in https://github.com/nicola-decao/KnowledgeEditor. At the same time, we also welcome you to explore adding KE to EasyEdit and provide corresponding PR, etc. Thank you again for your attention.
