### ISSUE TITLE
The results of GPT-J in Counterfact dataset.

### ISSUE THREAD

**Issue by Junyiliu0** [zjunlp/EasyEdit#125]
All in all :The results is different from the memit.
As you mentioned the results in easyedit use model GPT-J dataset using Counterfact is:
99.90,73.13,97.17. But the results in MEMIT paper shows 98.9 88.6 73.7. 
More importantly, I have observed your code, and I believe the metric you are using is accuracy (acc). However, in MEMIT, the metric used is actually the success  metric（not acc). If the accuracy metric is applied in MEMIT, the accuracy results I obtained with its source code after 10,000 editing in one time are: 96.02，54.85，11.84

So how gain the gap between your paper and memit in Counterfact dataset?
My issues:
1.I downloaded the dataset provided by you. Regarding the results for the Counterfact dataset in Table 1, could you please specify which version you used and provide details on how it was processed?
<img width="525" alt="image" src="https://github.com/zjunlp/EasyEdit/assets/100564143/af343e37-8b20-44fd-bbef-a642bc87cab8">

2.For the test, how many sample did you use for editing? I mean the memit can edit 10000 samples in one time, so for table one you use the same num?

3.For zsre the MEMIT locality acc is only 26.7%. How did you get 99.62?

**Comment by pengzju** [comment]
- Q1: As shown in the figure, in counterfact, there are three parts `edit`, `train`, `val`, where we use the `edit` dataset for model editing. You don't need any specific processing, just follow the default input.
- Q2: In our paper, we mentioned that Table1 shows a result of **n = 1** (that is, the model will fall back to the original weight after editing a sample). If you want to get results about sequential, batch edits, see **section 4.2** of the paper, where we also found a problem with memit damaging model weights after multiple edits.
- Q3: If you follow the Settings in Table1, you can get 99.62 results. But it may not be exactly equal, because there is a small (maybe +-2%) performance fluctuation due to the impact of the GPU and various pip package versions. You just need to set `keep_original_weight` to `False`

Other Problems:
MEMIT uses a `success metric` and we use token-level `accuracy`. This is because we have redefined the concept of model editing in the paper, that is, forcing the model to output the expected result, and both metrics are assessments of model editing, just in different ways.

**Comment by pengzju** [comment]
Thank you for your attention. Please contact me if you have any other questions. 😊

**Comment by Junyiliu0** [comment]
Thank you for your reply.I just test the editing num = 10000 for one time, so I got different result. Thanks!
And I think the "acc" metric is more reasonable and aligns better with the task definition compared to the "success" metric.
