### ISSUE TITLE
Issue about multimodal editing

### ISSUE THREAD

**Issue by haohaodw** [zjunlp/EasyEdit#126]
Hello, I am very interested in your multimodal editing work, but the exact results of M-Generality are not shown in Table 2 in this work. Although there are related figure later to display this indicator, it is difficult to make comparisons for future work. I noticed that some researchers have asked similar questions before. You said you would announce it as soon as possible, but it seems that the results have not been made public yet?

**Comment by cheng-siyuan** [comment]
Thank you for your suggestion, we have updated the results in the README and you can compare with our results here.

**Comment by JH-Yin** [comment]
![image](https://github.com/zjunlp/EasyEdit/assets/121718452/884d6c16-0b72-4575-9418-8263e9861ffd)

Are you referring to this result? However, the paper uses 2 models (blip2 and minigpt4) and two tasks. Logically speaking, there should be 4 groups M-Generality.

**Comment by cheng-siyuan** [comment]
For Question 1: We have updated the results in the README document for your reference.
For Question 2: We previously identified some bugs in the code and have since fixed them, leading to an updated set of results. It's important to note that these updates do not alter the experiment's conclusion. For more detailed information, please refer to [issue](https://github.com/zjunlp/EasyEdit/issues/110).

**Comment by zxlzr** [comment]
Hi, do you have further questions?
