### ISSUE TITLE
Question about SERAC

### ISSUE THREAD

**Issue by yaohui120** [zjunlp/EasyEdit#154]
I see you ran the sequential editing using the method SERAC in paper 《Editing Large Language Models: Problems, Methods, and Opportunities》. I want to know how much samples you saved in experiments. Thank you.

**Comment by pengzju** [comment]
- As you can see in Figure 3 of the paper, the part about SERAC only shows the editing capacity of [1,10,100]. That means we save **100** sequential editing samples. 
- In theory, this number could be more, but you may need to modify the code at **scope classifier**, because the original implementation is to calculate the similarity between all samples and the current editing instance, you can segment the calculation and merge it, and theoretically explore editing performance on 1000 or more samples

**Comment by yaohui120** [comment]
Thank you for your answer.
