### ISSUE TITLE
keep_original_weights and sequential editing

### ISSUE THREAD

**Issue by paulyoussef** [zjunlp/EasyEdit#213]
I don't understand the relation between `keep_original_weights` and sequential editing. 
In this [issue](https://github.com/zjunlp/EasyEdit/issues/47), it is mentioned that: 

> When you **set keep_original_weights to False, the editing scene is sequential editing**

In another [issue](https://github.com/zjunlp/EasyEdit/issues/57), it is said that: 

> Perhaps you **set keep_original_weights to True, which reloads the original model after editing**.
> You can get the edited weights by setting keep_original_weights to False

Does this mean that I need to choose between 1. non-sequential edits where I don't get the edited model back, and 2. sequential edits where I get the edited model back? In other words, is it possible to do mass (non-sequential) editing (say with MEMIT), and get the edited (non-original) model back? 

And how should I set `batch_size`? Should it be equal to the total number of edits that I want to conduct ?

**Comment by pengzju** [comment]
1. In fact, if you set `keep_original_weight` to `True`, the parameters will be rolled back after each edit. The specific code is at [here](https://github.com/zjunlp/EasyEdit/blob/main/easyeditor/editors/editor.py#L304). You can discord the rollback code to get the model parameters after a single edit.
2. I understand the difference between batch editing and sequential editing you mentioned. If you want to edit multiple samples in a batch, you can use the `editor.batch_edit` interface to enter the editing method in the form of **chunks**. In this scenario, one by one evaluation will be performed after batch editing of multiple samples.
3. You can add `batch_size` in [`yaml`](https://github.com/zjunlp/EasyEdit/blob/main/hparams/MEMIT/llama-7b.yaml). It does not need to be an integer divisor of `num_edits` because we have performed special processing for last_batch.
    - `batch_size` < `num_edits`

**Comment by pengzju** [comment]
Sorry for the late reply (🏖️) to you, please feel free to contact me if you have any questions.

**Comment by paulyoussef** [comment]
Thanks for your response. Just to clarify: If I want to conduct 16 edits, and I set the batch_size to 8 in the yaml file. This means that after every 8 edits the parameters of the model will be rolled back to the original. Is my understanding correct ?

**Comment by pengzju** [comment]
Yes, that's correct
