### ISSUE TITLE
Questions about the models supported by the SERAC method.

### ISSUE THREAD

**Issue by BUGLI27** [zjunlp/EasyEdit#239]
As far as I know, the serac method does not make changes to the target model, but acts as a plug-in to distinguish whether the query is related to the editing knowledge or not, why do some models such as Qwen not support the serac method?

**Comment by xzwyyd** [comment]
Thank you for your interest. 😊 The SERAC method relies on a smaller model from the same series to assist with editing. When we integrated the Qwen model, we didn't have a suitable smaller model available in the same series, which is why SERAC wasn't supported at that time.  Your reminder is appreciated, and we will consider adding support for it in the future.

**Comment by BUGLI27** [comment]
About `The SERAC method relies on a smaller model from the same series to assist with editing.`
This smaller model is needed to reply questions related to the edit memory?

**Comment by zxlzr** [comment]
Yes, more details can be found in the SERAC paper.
