### ISSUE TITLE
ccks gpt2-xl 模型 为什么用roberta模型加载？

### ISSUE THREAD

**Issue by XuJianzhi** [zjunlp/EasyEdit#327]
https://github.com/zjunlp/EasyEdit/blob/main/examples/run_ccks_SafeEdit_gpt2-xl.py#L189
为什么用roberta模型加载训练后的gpt2-xl模型文件呢？

**Comment by mengrusun** [comment]
gpt2-xl is a vanilla LLM, which may generate toxic responses to adversarial inputs. Therefore, we aim to detoxify the vanilla LLM (gpt2-xl).  Besides, we should design a classifier (roberta) judge whether a response is toxic.
Note that we load the weights of the classifier (RoBERTa) instead of GPT-2 XL in line 189. You can check that the checkpoint path in line 189 is for the classifier (RoBERTa) rather than GPT-2 XL.

**Comment by zxlzr** [comment]
Do you have any further questions?
