### ISSUE TITLE
FT-M for batch edit?

### ISSUE THREAD

**Issue by YukinoshitaKaren** [zjunlp/EasyEdit#353]
I have tried `editor.edit`  for FT-M, and got excellent results. But when using `editor.batch_edit` ( batch size = 100), I got poor results. Is this method not adapted for batch edit, or does it require configuration changes (except batch size) compared to single edit?

**Comment by littlefive5** [comment]
The code doesn't support batch editing. We're trying to enhance it and will let you know when we finish.

**Comment by JizhanFang** [comment]
Our code does support batch processing for FT-M. I suspect that the results you observed may be due to either using a batch size that is too large or not setting the `objective_optimization` field to 'prompt_last.' You could try reducing the batch size and adjusting the setting to see if that improves performance. If you need further assistance, feel free to share your FT hyperparameter configuration, and we would be happy to help.

**Comment by JizhanFang** [comment]
Our code has supported batch processing for FT-M. I suspect that the results you observed may be due to either using a batch size that is too large or not setting the `objective_optimization` field to 'prompt_last.' You could try reducing the batch size and adjusting the setting to see if that improves performance. If you need further assistance, feel free to share your FT hyperparameter configuration, and we would be happy to help.

**Comment by YukinoshitaKaren** [comment]
But 'prompt_last.' is not for FT-M, 
```
# "prompt_last" corresponds to the results of FT-L.
# "target_new" corresponds to the results of FT-M.
```

**Comment by JizhanFang** [comment]
Our code has supported batch processing for FT-M. I suspect that the results you observed may be due to either using a batch size that is too large or not setting the `objective_optimization` field to 'target_new'. You could try reducing the batch size and adjusting the setting to see if that improves performance. If you need further assistance, feel free to share your FT hyperparameter configuration, and we would be happy to help.

**Comment by YukinoshitaKaren** [comment]
I have already sloved the promble by myself, thanks for you reply
