### ISSUE TITLE
[Feature Request] Support MQuAKE-2002 Dataset 

### ISSUE THREAD

**Issue by BingliangLi** [zjunlp/EasyEdit#371]
Hi, thank you for this great project, may i ask if there is a plan to support the MQuAKE-2002 dataset in the future? 
https://paperswithcode.com/dataset/mquake-2002

**Comment by zxlzr** [comment]
Thank you for your suggestion, we will support MQuAKE-2002 soon.

**Comment by JizhanFang** [comment]
Hello! We have initially integrated the MQuAKE-2002 dataset into EasyEdit. And this is the link: https://github.com/zjunlp/EasyEdit/blob/main/easyeditor/dataset/MQuAKE.py. However, since the multi-hop task settings of MQuAKE do not fully align with EasyEdit: in the MQuAKE dataset, a single sample can contain multiple pieces of knowledge that need to be edited at once, which is different from typical knowledge editing datasets where each sample contains only one piece of knowledge.
Our approach has been to combine multiple prompts, subjects, and target_new from a single sample into one, which may cause a small problem when using EasyEdit with MQuAKE. Specifically, you might see the following code:

```
if '{}' not in request['prompt']:
    assert request['subject'] in request['prompt'] or \
           print(f"Subject:{request['subject']} do not exist in prompt: {request['prompt']}")
   
    request['prompt'] = request['prompt'].replace(request['subject'], '{}')
```

Due to our implementation, this may lead to an error. To resolve this, you can simply comment out these lines of code, and it should run smoothly without taking up much of your time.
Thank you for your understanding!

**Comment by JizhanFang** [comment]
Hello, we now support editing for the MQuAKE-2002 dataset. You simply need to follow the steps I mentioned earlier: first, use the `dataset/MQuAKE.py` script to import the data, and then proceed with editing using the PROMPT-based method.
https://github.com/zjunlp/EasyEdit/blob/main/examples/PROMPT.md
