### ISSUE TITLE
Question of edit_func

### ISSUE THREAD

**Issue by LiuJinzhe-Keepgoing** [zjunlp/EasyEdit#420]
Hello, thanks for providing such excellent open source projects. I encountered several puzzles when reading the code. Thanks for your help: 

1. in editor.py, the line of code `edited _ model, weights _ copy, ICL _ examples = edit _ func (request)`. I am confused about the return values of this: edited_model, weights_copy, where edited_model is the overall weight of the model after an edit? So every time you go through the for loop, you re-edit the original model? Or do you always add new edits to the edited model? Is weights_copy the basic model parameter of the original GPT or llama corresponding to the modified part?  

2. Are `sequential _ edit` and `keep_original_weight` the same? I didn't find the keep_original_weight parameter used in `apply_rome_to_model` and `apply _ mememit _ to _ model`.  

3. I don't understand the relationship between `edit_func` and `edit_evaluation`. My understanding is that edit _ func uses a prompt in requests to edit model parameters every time, and then uses edit_evaluation to verify indicators in the whole requests?  

4. I can understand that every time you edit a prompt in requests through edit_func, the parameters of the model will be modified correspondingly. Do these edits not affect each other? Is it true that by saving `metrics, edited_model, _ = editor. edit (...)` in run_knowedit_llama2.py, the returned edited _ model is the model of n samples in the current data set?  Thank you for your answer.

I am a novice in knowledge editing. Please forgive me.

**Comment by JizhanFang** [comment]
1. Yes,  `edited_model` is the overall weight of the model after an edit. No, your statement was not entirely accurate. In the setting of sequential editing, the model returned after each edit becomes the object for the next edit, meaning that the model is updated progressively. However, in the case of singleton editing, the object being edited is always the original model, and each edit operates on the original state. Yes, the `edit_copy` parameter stores the original parameters of the model's modified parts, allowing the original model to be restored after the edits.
2. No, these two parameters are completely different. `Sequential_edit` refers to a specific editing task setting, while `keep_original_weight` is a boolean parameter that indicates whether to restore the original parameters after an edit. However, as you mentioned, this parameter is essentially no longer in use, which is why you didn't find it in rome and memit. This is perfectly normal.
3. The function edit_func is responsible for performing the editing operation, while edit_evaluation evaluates the model before and after the edit, such as assessing the accuracy of the edit, as well as the model's portability, locality, and other related metrics.
4. I'm not quite clear what you mean the edits influencing each other. In fact, If the task setting is single editing, then these edits will not affect each other because the model reverts to its original weights after each edit; whereas if it's set to sequential editing, these edits will continuously alter the model's parameters. Regarding your last question, I suspect you might be asking whether the `edited_model` obtained from run_knowedit_llama2.py is the model after n edits. If sequential editing is configured, then what you get is indeed the model after n edits. However, if it is not set this way, then this `edited_model` would be the original model.

**Comment by zxlzr** [comment]
hi, do you have any further issues?
