### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory: 'data'

### ISSUE THREAD

**Issue by zjq0455** [zjunlp/EasyEdit#452]
Hi authors，I tried to evaluate the performance, but this error occurred. Do you know why this happen?

![1734660339781](https://github.com/user-attachments/assets/67b05f05-37e9-4978-bf02-624d6630346a)

**Comment by JizhanFang** [comment]
Hello, the 'data_dir' field in EasyEdit should be set to a specific file path name, for example, it should be specific to **counterfact.json**, not a folder or a dictionary.

**Comment by JizhanFang** [comment]
Hello, the 'data_dir' field in run_knowedit_llama2.py should be set to a specific file path name, for example, it should be specific to **counterfact.json**, not a folder or a dictionary.

**Comment by zjq0455** [comment]
Thank you for your positive reply!!!  I am a rookie in Knowledge editing,  I would like to inquire which file I should select if I just want to evaluate the performance of each technique (is the **xx_test.json** in each folder?) and if I want to perform editing using different approaches (is the **xx_train.json** in each folder?)?

**Comment by JizhanFang** [comment]
Hello, we divide the **training set** and the **test set** because some editing methods need to be trained in advance, such as serac method. Other methods are basically plug-and-play and do not need to be trained in advance, so you only need to choose train.json or test.json according to your own needs. Both datasets can be edited and evaluated.

**Comment by zjq0455** [comment]
Thank you very much for your valuable response! I have no further question.
