### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory

### ISSUE THREAD

**Issue by 18600709862** [zjunlp/EasyEdit#8]
please help:
code is:

hparams = MENDTrainingHparams.from_hparams("./hparams/TRAINING/MEND/llama-7b.yaml")
    train_ds = ZsreDataset('./Data/zsre/zsre_mend_train_10000.json', config=hparams)
    eval_ds = ZsreDataset('./Data/zsre/zsre_mend_eval.json', config=hparams)
    trainer = EditTrainer(
        config=hparams,
        train_set=train_ds,
        val_set=eval_ds
    )
    trainer.run()

run error：

File "EasyEdit/easyeditor/trainer/algs/MEND.py", line 285, in edit
    loss.backward()

OutOfMemoryError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 7; 79.19 GiB total capacity; 35.57 GiB already allocated; 14.88 MiB free; 35.63 
GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for
Memory Management and PYTORCH_CUDA_ALLOC_CONF

llama7b modle ,local path

thank you!
非常好的开源，在实验的时候发现报错，请求帮助，十分感谢！

**Comment by pengzju** [comment]
Thanks for your interest in EasyEdit, you encountered this bug due to memory overflow caused by backpropagation.

From a practical point of view, you'll need about `60-80 GB` of VRAM to train `llama-2-7B` using MEND.
You can refer to the following solutions:
1. Increase VRAM
2. Use `accelerate`  (https://github.com/huggingface/accelerate) for the model parallel
3. Change to another editing method (such as `ROME`)
